### PR TITLE
[GH-236] - restart netfilter service

### PR DESCRIPTION
**Pull request by hamarituc**
# Description

This PR ensures the netfilter service is restarted in iptables mode when firewall rules are changes.

## Issues Resolved

* #236

## Check List

- [x] All tests pass. See TESTING.md for details.
- [ ] ~~New functionality includes testing.~~ (not applicable, no new functionality)
- [ ] ~~New functionality has been documented in the README if applicable.~~ (not applicable, no new functionality)

It may be worth to test the restart behavior. Unfortunately if have no clue how to do it, because it involves at least two converge cycles to test it. Suggestions are welcome.

### CODE REVIEW

**Comment by ramereth** [comment]
@hamarituc it looks like the test failures are legit and need to be addressed as they are not present on the `main` branch. Can you please fix it?

**Comment by ramereth** [comment]
@hamarituc can you please add a changelog entry?

**Comment by hamarituc** [comment]
> @hamarituc can you please add a changelog entry?

Sorry for the mistake. I understood the contributing guideline not to alter the changelog at all, but it referred to the version number only. I fixed it.

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [3.0.1](https://github.com/sous-chefs/firewall/releases/tag/3.0.1)

**Pull request merged**
