### PR TITLE
Update provider_firewall_firewalld.rb

### PR DESCRIPTION
**Pull request by athiede-vendavo**
Documentation says `FirewallD - Red Hat & CentOS >= 7.0` but on RHEL/Alma/Rocky 8 it defaults to iptables. This should fix that.

### CODE REVIEW

**Comment by damacus** [comment]
Needs #248 before we can merge 👍🏼

**Comment by damacus** [comment]
Can you please provide a changelog entry for this fix thanks! 👍🏼

**Comment by athiede-vendavo** [comment]
I've added a changelog entry. Sorry it took a while!

**Review by damacus — DISMISSED** [review]

**Comment by jblaine** [comment]
Hi @damacus and @athiede-vendavo -- This never made it into main 14 months ago and the lack of it makes this cookbook not usable on RHEL 8 with firewalld intended.

**Comment by djessich** [comment]
What is the current status?
Firewall cookbook is not usable on RHEL/CentOS/Alma/Rocky 8 and 9.

**Review by bmhughes — DISMISSED** [review]

**Comment by kitchen-porter** [comment]
Released as: [6.3.0](https://github.com/sous-chefs/firewall/releases/tag/6.3.0)

**Pull request merged**
